test-script: Add actions test

diff --git a/tests/mousepad-test b/tests/mousepad-test
--- a/tests/mousepad-test
+++ b/tests/mousepad-test
@@ -300,6 +300,178 @@ test_gsettings ()
   rm "$out" "$bak"
 }
 
+# About the string variables 'included' 'excluded' and 'extrawins', and the array variables
+# 'prereqs' 'postprocs' and 'param_actions' below:
+# * 'included' and 'excluded' are ERE passed to awk to filter the action list provided by gdbus,
+#   so remember to double-escape characters when needed, e.g. '\\.' for a litteral dot.
+# * 'extrawins' is an ERE passed to bash to know which actions generate an extra window to be
+#   closed, so do not double-escape characters here, e.g. '\.' for a litteral dot.
+# * 'prereqs' and 'postprocs' are pairs (action - prerequisites/postprocesses), where:
+#   * 'action' is an action name
+#   * 'prerequisites/postprocesses' are sequences of actions separated by '\n', to be run
+#     before/after the above action during the test process.
+#   Example: prereqs=('edit.paste' 'edit.select-all\nedit.copy')
+# * 'param_actions' are pairs (action - param), where:
+#   * 'action' is an action name
+#   * 'param' is the parameter to pass to the above action (typically for radio actions)
+#   Example: 'document.filetype' "<'sh'>"
+# NB: actions are sorted at the output of `gdbus | awk`, so the above array variables must be
+#     pre-sorted (they are browsed only once).
+test_actions ()
+{
+  local    out type=$1 included excluded extrawins action param
+  local -a cmd prereqs postprocs param_actions actions
+  local -i r pid main_id id m=0 n
+
+  # exit if ever the previous mousepad instance didn't terminate
+  [ -n "$(pgrep -x mousepad)" ] && abort 'running'
+
+  # log and run the mousepad command
+  shift
+  out=$(mktemp) || abort 'file'
+  log_and_run_mousepad "$out" "$@"
+
+  # wait for the window to appear on screen, meaning mousepad is idle
+  main_id=$($timeout xdotool search --sync --onlyvisible --pid $pid | head -1) 2>&1
+
+  # a working mousepad is a prerequisite here
+  if ((main_id != 0)); then
+    case $type in
+    '--off-menu')
+      included='font-size'
+      excluded='^[^.]+\\.'
+      extrawins='$^'
+    ;;
+    '--file')
+      included='^file\\.'
+      excluded='\\.(new-from-template\\.new|open-recent\\.new|close-window)$'
+      extrawins='\.(open|open-recent\.clear-history|save-as|print|new-window|detach-tab)$'
+      prereqs=('file.close-tab' 'file.new' 'file.detach-tab' 'file.new')
+      postprocs=('file.new' 'file.close-tab')
+    ;;
+    '--edit')
+      included='^edit\\.'
+      excluded='\\.(paste-from-history|select-all|undo)$'
+      prereqs=(
+        'edit.copy' 'edit.select-all' 'edit.cut' 'edit.select-all'
+        'edit.paste' 'edit.select-all\nedit.copy'
+        'edit.paste-special.paste-as-column' 'edit.select-all\nedit.copy' 'edit.redo' 'edit.undo'
+      )
+      postprocs=(
+        'edit.convert.spaces-to-tabs' 'edit.undo' 'edit.convert.tabs-to-spaces' 'edit.undo'
+        'edit.cut' 'edit.undo' 'edit.delete-selection' 'edit.undo' 'edit.redo' 'file.save'
+      )
+      extrawins='$^'
+
+      # we need the view to be focused for some actions, but don't abort if that fails
+      xdotool windowfocus $main_id 2>&1
+    ;;
+    '--search')
+      included='^search\\.'
+      excluded='$^'
+      extrawins='\.(find-and-replace|go-to)$'
+    ;;
+    '--view')
+      included='^view\\.|bar-visible$'
+      excluded='$^'
+      postprocs=(
+        'preferences.window.menubar-visible' 'preferences.window.menubar-visible'
+        'preferences.window.statusbar-visible' 'preferences.window.statusbar-visible'
+        'preferences.window.toolbar-visible' 'preferences.window.toolbar-visible'
+        'view.fullscreen' 'view.fullscreen'
+      )
+      extrawins='\.select-font$'
+    ;;
+    '--document')
+      included='^document'
+      excluded='$^'
+      prereqs=('document' 'file.new')
+      postprocs=(
+        'document.go-to-tab' 'document.go-to-tab'
+        'document.viewer-mode' 'document.viewer-mode'
+        'document.write-unicode-bom' 'document.write-unicode-bom\nfile.save'
+      )
+      extrawins='\.tab\.tab-size$'
+      param_actions=(
+        'document.filetype' "<'sh'>" 'document.go-to-tab' '<1>' 'document.go-to-tab' '<0>'
+        'document.line-ending' '<1>' 'document.tab.tab-size' '<0>'
+      )
+    ;;
+    '--help')
+      included='^help\\.'
+      excluded='\\.contents$'
+      extrawins='\.about$'
+    ;;
+    *)
+      # try to quit gracefully and abort
+      "$mousepad" --quit
+      abort "${FUNCNAME[0]}(): Wrong argument '$type'"
+    ;;
+    esac
+
+    # filter action list
+    mapfile -t actions < <(
+      gdbus call --session --dest org.xfce.mousepad --object-path /org/xfce/mousepad/window/1 \
+      --method org.gtk.Actions.List | sed "s/(\['\|'\],)//g; s/', '/\n/g" | sort \
+      | awk -v inc="$included" -v exc="$excluded" -v _pre="${prereqs[*]}" -v _post="${postprocs[*]}" '
+        BEGIN { split (_pre, pre, "[ ]"); split (_post, post, "[ ]"); m = n = 1 }
+        ($0 ~ inc && $0 !~ exc) {
+          if ($0 == pre[m]) { print pre[++m]; m++ }
+          print
+          if ($0 == post[n]) { print post[++n]; n++ }
+        }'
+    )
+
+    for action in "${actions[@]}"; do
+      # purge the logs and run the gdbus command
+      purge_logs "$out"
+      ((n_cmds++))
+      param=''
+      [ "${param_actions[m]}" = "$action" ] && {
+        param=${param_actions[++m]}
+        ((m++))
+      }
+
+      echo "Command $n_cmds: gdbus call ... $action \"[$param]\" '{}'" | duperr
+      gdbus call --session --dest org.xfce.mousepad --object-path /org/xfce/mousepad/window/1 \
+        --method org.gtk.Actions.Activate "$action" "[$param]" '{}' >/dev/null &
+
+      # wait for the end of the action when possible
+      timeout 3 pwait -x gdbus
+
+      # when needed, wait for the new window (main or dialog) to appear on screen and close it
+      [[ $action =~ $extrawins ]] && {
+        for ((n = 1; ; n++)); do
+          id=$(xdotool search --sync --onlyvisible --pid $pid 2>/dev/null | tail -1)
+          ((id != main_id && id != 0)) && {
+            wmctrl -i -c $id
+            break
+          }
+
+          ((n == 10)) && abort "${FUNCNAME[0]}(): Waiting time exceeded"
+          sleep 1
+        done
+      }
+    done
+
+    # purge the logs and run the quit command
+    purge_logs "$out"
+    log_and_run_mousepad --quit
+  else
+    wait_and_term_mousepad
+  fi
+
+  # send KILL signal if needed
+  wait_and_kill_mousepad $pid
+  r=$?
+
+  # log results
+  log_results "$out" "$r"
+
+  # cleanup
+  rm "$out"
+}
+
 section_is_enabled ()
 {
   local regex section parent
@@ -362,6 +534,8 @@ section_list=(
   'simple-gui' 'simple-gui.no-file' 'simple-gui.one-file' 'simple-gui.multi-file'
   'gsettings' 'gsettings.no-file' 'gsettings.preferences' 'gsettings.one-file'
               'gsettings.multi-tab' 'gsettings.multi-window'
+  'actions' 'actions.off-menu' 'actions.file' 'actions.edit' 'actions.search'
+            'actions.view' 'actions.document' 'actions.help'
 )
 
 while [ "$1" != '--' ]; do
@@ -541,6 +715,48 @@ section_is_enabled 'gsettings.multi-window' && {
   echo '- Multi-window -' | duperr
   create_tempfiles 2
   test_gsettings --opening-mode=window -- "${tempfiles[@]}"
+}
+
+# Actions (for the moment (Mousepad 0.5.5) only window actions are relevant: application actions
+# are tested via gsettings or command line options above)
+section_is_enabled --sub 'actions' && {
+  create_tempfiles 1
+  printf '\n%s\n' '*** Action commands ***' | duperr
+}
+
+section_is_enabled 'actions.off-menu' && {
+  echo '- Off-menu -' | duperr
+  test_actions --off-menu "${tempfiles[0]}"
+}
+
+section_is_enabled 'actions.file' && {
+  echo '- File menu -' | duperr
+  test_actions --file "${tempfiles[0]}"
+}
+
+section_is_enabled 'actions.edit' && {
+  echo '- Edit menu -' | duperr
+  test_actions --edit "${tempfiles[0]}"
+}
+
+section_is_enabled 'actions.search' && {
+  echo '- Search menu -' | duperr
+  test_actions --search "${tempfiles[0]}"
+}
+
+section_is_enabled 'actions.view' && {
+  echo '- View menu -' | duperr
+  test_actions --view "${tempfiles[0]}"
+}
+
+section_is_enabled 'actions.document' && {
+  echo '- Document menu -' | duperr
+  test_actions --document "${tempfiles[0]}"
+}
+
+section_is_enabled 'actions.help' && {
+  echo '- Help menu -' | duperr
+  test_actions --help "${tempfiles[0]}"
 }
 
 # Outcome
