test-script: Add gsettings test

diff --git a/tests/mousepad-test b/tests/mousepad-test
--- a/tests/mousepad-test
+++ b/tests/mousepad-test
@@ -62,6 +62,8 @@ cleanup ()
 
 abort ()
 {
+  local files
+
   printf '\n%s\n' '*** Aborted ***' | duperr
 
   case $1 in
@@ -76,6 +78,12 @@ abort ()
   ;;
   esac | duperr
 
+  # see if some backup files were kept
+  shopt -s nullglob
+  files=("$logdir/"*.bak)
+  [ -n "$files" ] \
+    && echo "Some '.bak' files to restore Mousepad configuration were kept in $logdir" | duperr
+
   cleanup
 
   exit 1
@@ -88,6 +96,15 @@ filter ()
   else
     grep -E -v "${ignored[@]}"
   fi
+}
+
+purge_logs ()
+{
+  [ -s "$1" ] && {
+    warnings[n_warns++]=$n_cmds
+    sed 's/^/  /' <"$1"
+    >"$1"
+  }
 }
 
 test_non_gui ()
@@ -146,14 +163,8 @@ test_simple_gui ()
   # quit as gracefully as possible, testing `mousepad --quit` in various contexts by the way
   if ((id != 0)); then
     if [[ $* != *--disable-server* ]]; then
-      # purge the logs
-      [ -s "$out" ] && {
-        warnings[n_warns++]=$n_cmds
-        sed 's/^/  /' <"$out"
-        >"$out"
-      }
-
-      # log and run the quit command
+      # purge the logs and run the quit command
+      purge_logs "$out"
       ((n_cmds++))
       echo "Command $n_cmds: $mousepad --quit" | duperr
       $timeout "$mousepad" --quit 2>&1
@@ -189,6 +200,94 @@ test_simple_gui ()
 
   # cleanup
   rm "$out"
+}
+
+test_gsettings ()
+{
+  local    out bak schema key value
+  local -a cmd schemas keys values
+  local -i r pid id n
+
+  # exit if ever the previous mousepad instance didn't terminate
+  [ -n "$(pgrep -x mousepad)" ] && abort 'running'
+
+  # store current configuration and mark all settings as manually set, so that
+  # reseting them afterwards will always trigger the corresponding mousepad handlers
+  bak="$logdir/$script_name.gsettings.bak"
+  (>"$bak") || abort 'file'
+  gsettings list-recursively org.xfce.mousepad | sort >"$bak"
+
+  while read schema key value; do
+    schemas+=("$schema")
+    keys+=("$key")
+    values+=("$value")
+    gsettings set "$schema" "$key" "$value"
+  done <"$bak"
+
+  # log and run the mousepad command
+  cmd=("$mousepad" "$@")
+  ((n_cmds++))
+  echo "Command $n_cmds: ${cmd[*]}" | duperr
+
+  out=$(mktemp) || abort 'file'
+  "${cmd[@]}" 2> >(filter >"$out") 1>/dev/null &
+  pid=$!
+
+  # wait for the window to appear on screen, meaning mousepad is idle
+  id=$($timeout xdotool search --sync --onlyvisible --pid $pid | head -1) 2>&1
+
+  # a working mousepad is a prerequisite here
+  if ((id != 0)); then
+    for n in ${!schemas[@]}; do
+      # purge the logs and run the gsettings command
+      purge_logs "$out"
+      ((n_cmds++))
+      echo "Command $n_cmds: gsettings reset ${schemas[n]} ${keys[n]}" | duperr
+      gsettings reset "${schemas[n]}" "${keys[n]}"
+
+      # give mousepad some time to handle the setting change
+      sleep 1
+    done
+
+    # purge the logs and run the quit command
+    purge_logs "$out"
+    ((n_cmds++))
+    echo "Command $n_cmds: $mousepad --quit" | duperr
+    $timeout "$mousepad" --quit 2>&1
+  else
+    pkill -x mousepad
+  fi
+
+  # send KILL signal if needed
+  wait $pid
+  r=$?
+  ((r >= 124)) && {
+    $timeout pwait -x mousepad 2>&1 &
+    pid=$!
+    pkill -9 -x mousepad
+    wait $pid
+    r=$?
+  }
+
+  # restore the settings
+  for n in ${!schemas[@]}; do
+    gsettings set "${schemas[n]}" "${keys[n]}" "${values[n]}"
+  done
+
+  # log results
+  [ -s "$out" ] && {
+    warnings[n_warns++]=$n_cmds
+    sed 's/^/  /' <"$out"
+    printf '%s\n\n' "Exit code: $r"
+  }
+
+  ((r != 0)) && {
+    errors[n_errs++]=$n_cmds
+    [ ! -s "$out" ] && printf '%s\n\n' "Exit code: $r"
+  }
+
+  # cleanup
+  rm "$out" "$bak"
 }
 
 section_is_enabled ()
@@ -236,7 +335,7 @@ create_tempfiles ()
 declare -r timeout='timeout -v -k 5 -- 10' script_name=${0##*/}
 declare -a sections ignored warnings errors tempfiles
 declare -i quiet=0 n_warns=0 n_errs=0 n_cmds=0
-declare    mousepad logfile
+declare    mousepad logfile logdir
 
 # Option parsing
 temp=$(getopt -o 'hqc:l:s:i:' \
@@ -249,6 +348,8 @@ eval set -- "$temp" && unset temp
 section_list=(
   'non-gui'
   'simple-gui' 'simple-gui.no-file' 'simple-gui.one-file' 'simple-gui.multi-file'
+  'gsettings' 'gsettings.no-file' 'gsettings.preferences' 'gsettings.one-file'
+              'gsettings.multi-tab' 'gsettings.multi-window'
 )
 
 while [ "$1" != '--' ]; do
@@ -322,12 +423,13 @@ which "$mousepad" &>/dev/null || {
 }
 
 logfile=${logfile:-"$PWD/$script_name.log"}
+logdir=$(dirname "$logfile")
 [ -d "$logfile" ] && {
   printerr 'error' "'$logfile' is a directory"
   exit 1
 }
-[ ! -w "$(dirname "$logfile")" ] && {
-  printerr 'error' "Directory '$(dirname "$logfile")' is read-only"
+[ ! -w "$logdir" ] && {
+  printerr 'error' "Directory '$logdir' is read-only"
   exit 1
 }
 
@@ -346,8 +448,14 @@ which wmctrl &>/dev/null || {
   exit 1
 }
 
+[ -z "$sections" ] && {
+  read -s -n1 -p 'Are you sure you want to run all the test sections, this could take a while? ([y]es, [N]o) '
+  echo $REPLY
+  [[ $REPLY != [yY] ]] && exit 0 || echo
+}
+
 # Set some global constants
-readonly quiet mousepad logfile sections ignored
+readonly quiet mousepad logfile logdir sections ignored
 
 # From now on we write by default in the logfile
 exec 1>"$logfile"
@@ -389,6 +497,29 @@ section_is_enabled 'simple-gui.multi-file' && {
   create_tempfiles 2
   test_simple_gui --opening-mode=tab -- "${tempfiles[@]}"
   test_simple_gui --opening-mode=window -- "${tempfiles[@]}"
+}
+
+# GSettings (setting change from cli when mousepad is running)
+section_is_enabled --sub 'gsettings' \
+  && printf '\n%s\n' '*** GSettings commands ***' | duperr
+
+section_is_enabled 'gsettings.no-file' && test_gsettings
+
+section_is_enabled 'gsettings.preferences' && test_gsettings --preferences
+
+section_is_enabled 'gsettings.one-file' && {
+  create_tempfiles 1
+  test_gsettings "${tempfiles[0]}"
+}
+
+section_is_enabled 'gsettings.multi-tab' && {
+  create_tempfiles 2
+  test_gsettings --opening-mode=tab -- "${tempfiles[@]}"
+}
+
+section_is_enabled 'gsettings.multi-window' && {
+  create_tempfiles 2
+  test_gsettings --opening-mode=window -- "${tempfiles[@]}"
 }
 
 # Outcome
